spring:
  application:
    name: virta
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:virtadb
    username: user
    password: password
  liquibase:
    enabled: true
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK
    change-log: classpath:db/changelog/liquibase-master.xml
    user: user
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  servlet:
    context-path: /virta

